add check for paramator

diff --git a/bin/keyadd-peco b/bin/keyadd-peco
--- a/bin/keyadd-peco
+++ b/bin/keyadd-peco
@@ -2,7 +2,12 @@
 
 ssh_dir="$HOME/.ssh"
 
-key_to_add=`ls "$ssh_dir" | grep -v config | grep -v .pub | grep -v known_hosts | peco`
+key_to_add=`ls "$ssh_dir" | grep -v config | grep -v .pub | grep -v known_hosts | peco --prompt='PRVKEY>'`
 
-ssh-add "$ssh_dir/$key_to_add"
+if [ "$key_to_add" != "" ] ; then
+  ssh-add "$ssh_dir/$key_to_add"
+else
+  echo 'abort'
+  exit 1
+fi
 
