fix indent

diff --git a/bin_x/kmap b/bin_x/kmap
--- a/bin_x/kmap
+++ b/bin_x/kmap
@@ -3,38 +3,38 @@
 xmodmap_dir="$HOME/.xmodmap.d"
 
 if [ ! "${1:+heyyeyaaeyaaaeyaeyaa}" = heyyeyaaeyaaaeyaeyaa ] ; then
-    # interactive mode
-    index=0
-    for filepath in $xmodmap_dir/* ; do
-        xmodmap_files+=($filepath) 
-        echo "$index: $filepath"
-        index=`expr $index + 1`
-    done
-    while [ true ] ; do
-        echo -n "Config to apply (0-`expr $index - 1`): "
-        read ans
-        if [ $ans -gt -1 -a $ans -lt $index ] ; then
-            echo "Applying ${xmodmap_files[$ans]}..."
-            xmodmap "${xmodmap_files[$ans]}"
-            break
-        else
-            echo "Wrong input: $ans"
-        fi
-    done
+  # interactive mode
+  index=0
+  for filepath in $xmodmap_dir/* ; do
+    xmodmap_files+=($filepath) 
+    echo "$index: $filepath"
+    index=`expr $index + 1`
+  done
+  while [ true ] ; do
+    echo -n "Config to apply (0-`expr $index - 1`): "
+    read ans
+    if [ $ans -gt -1 -a $ans -lt $index ] ; then
+      echo "Applying ${xmodmap_files[$ans]}..."
+      xmodmap "${xmodmap_files[$ans]}"
+      break
+    else
+      echo "Wrong input: $ans"
+    fi
+  done
 else
-    # apply args
-    while [ true ]; do
-        if [ -e $xmodmap_dir/$1 ] ; then
-            echo "Loading keymap: $1"
-            xmodmap $xmodmap_dir/$1
-        else
-            echo "Error: There is no keymap file named $1"
-            exit 1
-        fi
-        if [ "${2:+heyyeyaaeyaaaeyaeyaa}" = heyyeyaaeyaaaeyaeyaa ] ; then
-            shift
-        else
-            break
-        fi
-    done
+  # apply args
+  while [ true ]; do
+    if [ -e $xmodmap_dir/$1 ] ; then
+      echo "Loading keymap: $1"
+      xmodmap $xmodmap_dir/$1
+    else
+      echo "Error: There is no keymap file named $1"
+      exit 1
+    fi
+    if [ "${2:+heyyeyaaeyaaaeyaeyaa}" = heyyeyaaeyaaaeyaeyaa ] ; then
+      shift
+    else
+      break
+    fi
+  done
 fi
