now can treat plural args

diff --git a/scripts/kmap b/scripts/kmap
--- a/scripts/kmap
+++ b/scripts/kmap
@@ -3,7 +3,8 @@
 xmodmap_dir="$HOME/.xmodmap.d"
 
 if [ ! "${1:+heyyeyaaeyaaaeyaeyaa}" = heyyeyaaeyaaaeyaeyaa ] ; then
-    index=0
+		# interactive mode
+		index=0
     for filepath in $xmodmap_dir/* ; do
         xmodmap_files+=($filepath) 
 				echo "$index: $filepath"
@@ -21,17 +22,19 @@ if [ ! "${1:+heyyeyaaeyaaaeyaeyaa}" = heyyeyaaeyaaaeyaeyaa ] ; then
         fi
     done
 else
-    if [ ! -e $xmodmap_dir ] ; then
-        echo '"There is no xmodmap file in home directory.'
-    else
-        if [ -e $xmodmap_dir/$1 ] ; then
-            echo "Loading keymap: $1"
-            xmodmap $xmodmap_dir/$1
-        else
-            echo "There is no keymap file named $1"
-            echo "Abort"
-            exit 1
-        fi
-    fi
+		# apply args
+		while [ true ]; do
+				if [ -e $xmodmap_dir/$1 ] ; then
+						echo "Loading keymap: $1"
+						xmodmap $xmodmap_dir/$1
+				else
+						echo "Error: There is no keymap file named $1"
+						exit 1
+				fi
+				if [ "${2:+heyyeyaaeyaaaeyaeyaa}" = heyyeyaaeyaaaeyaeyaa ] ; then
+						shift
+				else
+						break
+				fi
+    done
 fi
-
